id = "Branch"
icon = "lucide/git-branch.svg"
label.en = "Branch"

[[card]]
query = """
WITH ranked_rows AS (
    SELECT *, ROW_NUMBER() OVER (PARTITION BY id ORDER BY date_time DESC) AS row_num
    FROM Branch_time_series_parameters
    WHERE date_time < (SELECT initial_date_time FROM Configuration LIMIT 1)
)
SELECT COUNT(*)
FROM ranked_rows
WHERE row_num = 1 AND existing = 1;
"""
type = "integer"
label.en = "Existing Elements"
unit = "unit(s)"

[[card]]
query = """
WITH ranked_rows AS (
    SELECT *, ROW_NUMBER() OVER (PARTITION BY id ORDER BY date_time DESC) AS row_num
    FROM Branch_time_series_parameters
    WHERE date_time < (SELECT initial_date_time FROM Configuration LIMIT 1)
)
SELECT SUM(capacity) AS total_capacity
FROM ranked_rows
WHERE row_num = 1 AND existing = 1;
"""
type = "double"
format = "{:.1f}"
label.en = "Total Capacity"
unit = "MW"

[[card]]
query = "SELECT COUNT(*) FROM Branch_time_series_parameters"
type = "integer"
label.en = "Temporal Entries"
unit.en = "record(s)"

[[attribute]]
id = "label"
label.en = "Label"
tooltip.en = "Label of the branch"

[[attribute]]
id = "line_model"
type = "enum"
enum = "line_model"
label.en = "Line Model"
tooltip.en = "Line model of the branch"

[[attribute]]
id = "bus_to"
label.en = "Bus To"
tooltip.en = "Bus to of the branch"

[[attribute]]
id = "bus_from"
label.en = "Bus From"
tooltip.en = "Bus from of the branch"

[[attribute_group]]
id = "parameters"
label.en = "Parameters"
icon = "lucide/settings-2.svg"

[[attribute]]
id = "date_time"
label.en = "Date Time"
tooltip.en = "Date time of the branch"
unit = "yyyy-MM-dd HH:mm"

[[attribute]]
id = "existing"
type = "enum"
enum = "existing"
label.en = "Existing"
tooltip.en = "Existing of the branch"

[[attribute]]
id = "capacity"
label.en = "Capacity"
tooltip.en = "Capacity of the branch"
unit = "MW"

[[attribute]]
id = "reactance"
label.en = "Reactance"
tooltip.en = "Reactance of the branch"
unit = "p.u."
