id = "Bus"
icon = "lucide/circle-small.svg"
label.en = "Bus"

[[card]]
query = "SELECT COUNT(*) FROM Bus"
type = "integer"
label.en = "Elements"
unit.en = "bus(es)"

[[attribute]]
id = "label"
label.en = "Label"
tooltip.en = "Label of the bus"

[[attribute]]
id = "zone_id"
label.en = "Zone"
tooltip.en = "Zone of the bus"

[[attribute]]
id = "latitude"
label.en = "Latitude"
tooltip.en = "Latitude of the bus"

[[attribute]]
id = "longitude"
label.en = "Longitude"
tooltip.en = "Longitude of the bus"
