id = "DCLine"
icon = "lucide/spline.svg"
label.en = "DC Line"

[[card]]
query = """
WITH ranked_rows AS (
    SELECT *, ROW_NUMBER() OVER (PARTITION BY id ORDER BY date_time DESC) AS row_num
    FROM DCLine_time_series_parameters
    WHERE date_time < (SELECT initial_date_time FROM Configuration LIMIT 1)
)
SELECT COUNT(*)
FROM ranked_rows
WHERE row_num = 1 AND existing = 1;
"""
type = "integer"
label.en = "Existing Elements"
unit = "unit(s)"

[[card]]
query = """
WITH ranked_rows AS (
    SELECT *, ROW_NUMBER() OVER (PARTITION BY id ORDER BY date_time DESC) AS row_num
    FROM DCLine_time_series_parameters
    WHERE date_time < (SELECT initial_date_time FROM Configuration LIMIT 1)
)
SELECT SUM(
           CASE 
               WHEN capacity_to > capacity_from THEN capacity_to
               ELSE capacity_from
           END
       ) AS total_capacity
FROM ranked_rows
WHERE row_num = 1 AND existing = 1;
"""
type = "double"
format = "{:.1f}"
label.en = "Total Capacity"
unit = "MW"

[[card]]
query = "SELECT COUNT(*) FROM DCLine_time_series_parameters"
type = "integer"
label.en = "Temporal Entries"
unit.en = "record(s)"

[[attribute]]
id = "label"
label.en = "Label"
tooltip.en = "Label of the DC line"

[[attribute]]
id = "bus_to"
label.en = "Bus To"
tooltip.en = "Bus to of the DC line"

[[attribute]]
id = "bus_from"
label.en = "Bus From"
tooltip.en = "Bus from of the DC line"

[[attribute_group]]
id = "parameters"
label.en = "Parameters"
icon = "lucide/settings-2.svg"

[[attribute]]
id = "date_time"
label.en = "Date Time"
tooltip.en = "Date time of the DC line"
unit = "yyyy-MM-dd HH:mm"

[[attribute]]
id = "existing"
type = "enum"
enum = "existing"
label.en = "Existing"
tooltip.en = "Existing of the DC line"

[[attribute]]
id = "capacity_to"
label.en = "Capacity To"
tooltip.en = "Capacity to of the DC line"
unit = "MW"

[[attribute]]
id = "capacity_from"
label.en = "Capacity From"
tooltip.en = "Capacity from of the DC line"
unit = "MW"
