id = "DemandUnit"
icon = "lucide/zap.svg"
label.en = "Demand Unit"

[[card]]
query = """
WITH ranked_rows AS (
    SELECT *, ROW_NUMBER() OVER (PARTITION BY id ORDER BY date_time DESC) AS row_num
    FROM DemandUnit_time_series_parameters
    WHERE date_time < (SELECT initial_date_time FROM Configuration LIMIT 1)
)
SELECT COUNT(*)
FROM ranked_rows
WHERE row_num = 1 AND existing = 1;
"""
type = "integer"
label.en = "Existing Elements"
unit = "unit(s)"

[[card]]
query = "SELECT SUM(max_demand) FROM DemandUnit;"
type = "double"
format = "{:.1f}"
label.en = "Max Demand"
unit = "MW"

[[card]]
query = "SELECT COUNT(*) FROM DemandUnit_time_series_parameters"
type = "integer"
label.en = "Temporal Entries"
unit.en = "record(s)"

[[attribute]]
id = "label"
label.en = "Label"
tooltip.en = "Label of the demand unit"

[[attribute]]
id = "demand_unit_type"
type = "enum"
enum = "demand_type"
label.en = "Demand Type"
tooltip.en = "Demand type of the demand unit"

[[attribute]]
id = "max_shift_up"
label.en = "Max Shift Up"
tooltip.en = "Max shift up of the demand unit"
hide = true

[[attribute]]
id = "max_shift_down"
label.en = "Max Shift Down"
tooltip.en = "Max shift down of the demand unit"
hide = true

[[attribute]]
id = "curtailment_cost"
label.en = "Curtailment Cost"
tooltip.en = "Curtailment cost of the demand unit (if flexible demand)"
unit = "$/MWh"
hide = true

[[attribute]]
id = "max_curtailment"
label.en = "Max Curtailment"
tooltip.en = "Max curtailment of the demand unit (if flexible demand)"
hide = true

[[attribute]]
id = "bus_id"
label.en = "Bus"
tooltip.en = "Bus of the demand unit"

[[attribute]]
id = "max_demand"
label.en = "Max Demand"
tooltip.en = "Max demand of the demand unit"
unit = "MW"

[[attribute]]
id = "gaugingstation_downstream"
label.en = "Gauging Station Downstream"
tooltip.en = "Gauging station downstream of the demand unit"

[[attribute_group]]
id = "parameters"
label.en = "Parameters"
icon = "lucide/settings-2.svg"

[[attribute]]
id = "date_time"
label.en = "Date Time"
tooltip.en = "Date time of the demand unit"
unit = "yyyy-MM-dd HH:mm"

[[attribute]]
id = "existing"
type = "enum"
enum = "existing"
label.en = "Existing"
tooltip.en = "Existing of the demand unit"
