dimension_sizes = [ 1, 1, 2 ]
dimensions = [ 'period', 'scenario', 'subperiod' ]
frequencies = [ 'monthly' ]
initial_datetime = '2020-01-01T00:00:00'
labels = [ 'dem_1' ]
time_dimensions = [ 'period' ]
unit = 'p.u.'
version = '1'