# # Editing clearing options

# In this tutorial, it is described how to edit a case's clearing parameters, such as the market iterations considered in the execution (ex-ante 
# and/or ex-post), the nature of these procedures (physical or commercial), and their dispatch criteria (cost-based or bid-based). 
# For that, we will use as a starting point the `boto_base_01` example case in its default configuration - that is, disregarding any changes carried out 
# in previous tutorials. Firstly, we must rebuild this case from IARA's dataset (in order to "reset" its configuration) in the `case_path` previously informed
# (assuming that you have already gone through the previous tutorials). Then, we will load this study, using the [`IARA.load_study`](@ref) function, 
# and store it in a variable named `case_edit_clearing` (including the `read_only = false` argument to indicate that we wish to modify the case).

using IARA # hide
const case_path = joinpath(@__DIR__, "data", "ExampleCase_boto_base_01") # hide
case_name = "boto_base_01"
IARA.ExampleCases.build_example_case(case_path, case_name)
case_edit_clearing = IARA.load_study(case_path; read_only = false);
#hide

# The IARA model is capable of executing 4 dispatch types: (i) ex-ante physical dispatch, (ii) ex-ante commercial dispatch, 
# (iii) ex-post physical dispatch, and (iv) ex-post commercial dispatch. These correspond to procedures that can be executed by system 
# or market operators, depending on the regulatory framework and market design elements adopted, which vary case by case.
# For more information, click [here](../clearing_procedure.md) to access a detailed conceptual description of these dispatch procedures.

# Regardless of the regulatory framework that is being represented, all 4 steps must have their corresponding dispatch criterion (or execution mode) 
# defined, which can be: (i) skipped, when we do not want to represent the procedure, (ii) cost-based, when we wish to explictly represent the 
# unit's physical characteristics in the modelling, (iii) bid-based, when the units' parameters and their owners' strategies are translated into 
# price-quantity bids, or (iv) hybrid, when some agents are represented as cost-based, while other are represented as bid-based.

# In its default definition, the example case under analysis presents the following characteristics:

# | **Dispatch procedure** | **Execution mode** |
# |:----------------------:|:------------------:|
# |    Ex-ante physical    |        Skip        |
# |   Ex-ante commercial   |        Skip        |
# |    Ex-post physical    |     Cost-based     |
# |   Ex-post commercial   |        Skip        |

# Taking this case as a starting point, in order to modify its clearing characteristics, we can use the function [`IARA.update_configuration!`](@ref) 
# to adjust the execution mode of selected dispatch procedures (indicating firstly the variable in which the loaded case is stored). 
# In the example below, we change the execution mode of the ex-ante physical dispatch, from skip to cost-based.
# This means that we are adding an ex-ante dispatch iteration to the study, which had a single ex-post iteration until this point - 
# maintaining the cost-based nature of the study procedures.

IARA.update_configuration!(
    case_edit_clearing;
    construction_type_ex_ante_physical = IARA.Configurations_ConstructionType.COST_BASED,
)
; #hide

# Now, the execution mode of each dispatch procedure comprised in the example case is as follows:

# | **Dispatch procedure** | **Execution mode** |
# |:----------------------:|:------------------:|
# |    Ex-ante physical    |     Cost-based     |
# |   Ex-ante commercial   |        Skip        |
# |    Ex-post physical    |     Cost-based     |
# |   Ex-post commercial   |        Skip        |

# Note that this modification means that a whole new set of results will be generated by the model, with the outputs from the ex-ante 
# physical dispatch (alongside the ones from the ex-post physical dispatch, already discussed in the previous tutorials).

# When executing this case using the [`IARA.market_clearing`](@ref) function) - after closing the database and defining a path 
# for the model to write the execution outputs -, we obtain marginal costs shown below for the ex-ante and ex-post physical dispatches, respectively.
# In the case of the ex-post dispatch, the results are the same ones shown in the [first steps](case_building.md) tutorial (which used the `boto_base_01`
# example case in its default configuration), since no changes were made to this market iteration in the present analysis. 
# Comparing these results with the ones obtained for the ex-ante procedure, it is noticeable that the latter presents marginal costs with lower dispersion 
# among scenarios of a same period/subperiod. This is a natural consequence of the greater uncertainty inherent to real-time production and consumption 
# (represented in the ex-post iteration) when contrasted with ex-ante forecasts, which tend to present lower variability.

IARA.close_study!(case_edit_clearing)
path03_edit_clearing = joinpath(case_path, "03_edit_clearing")
IARA.market_clearing(case_path; output_path = path03_edit_clearing);
#hide

cmg_name_expost = "load_marginal_cost_ex_post_physical.csv"
cmg_name_exante = "load_marginal_cost_ex_ante_physical.csv"
cmg_path_expost = joinpath(path03_edit_clearing, cmg_name_expost)
cmg_path_exante = joinpath(path03_edit_clearing, cmg_name_exante)
; #hide
IARA.custom_plot(cmg_path_expost, IARA.PlotTimeSeriesQuantiles)
IARA.custom_plot(cmg_path_exante, IARA.PlotTimeSeriesQuantiles)

# The next step of this `Getting started` tutorial describes the (heuristic bid pre-processing) applied to dispatches executed in bid-based mode.
