version = 1
dimensions = ["period", "scenario", "subperiod", "bid_segment"]
dimension_size = [1, 1, 2, 1]
initial_date = "2020-01-01 00:00:00"
time_dimension = "period"
frequency = "month"
unit = "MWh"
labels = ["bg_1 - bus_1", "bg_2 - bus_1"]
