# # Virtual Reservoir - Running

# > The data for this case is available in the folder [`data/case_5`](https://github.com/psrenergy/IARA.jl/tree/main/docs/src/tutorial/data/case_5)

using Dates
using DataFrames
using IARA
; #hide

# ## Case recap

# In the [previous section](case_05_build_reservoir_case.md), we have built a case containing a virtual reservoir with two hydro units and two asset owners.
# Now we will run this case using the `MARKET_CLEARING` mode.

# As we have Hydro Units in this case, we need the hydro generation and hydro opportunity cost time series files. We can automatically generate them by running the case with the `TRAIN_MIN_COST` mode.
# We will be doing this before running the case in the `MARKET_CLEARING` mode.

# Let's create a folder to store the output of the `MARKET_CLEARING` mode and define the path to the original case.

const PATH_ORIGINAL = joinpath(@__DIR__, "data", "case_5")
const PATH_EXECUTION = joinpath(@__DIR__, "case_5_execution")

if !isdir(PATH_EXECUTION)
    mkdir(PATH_EXECUTION)
end

cp(PATH_ORIGINAL, PATH_EXECUTION; force = true);
#hide

# ## Executing

# ## Adding Hydro time series

# Now we are able to run the case with [`IARA.train_min_cost`](@ref).

IARA.train_min_cost(
    PATH_EXECUTION;
    delete_output_folder_before_execution = true,
)

# After that, we have to move the cost-to-go function cuts file to the `case_5_execution` folder.

fcf_cuts_file = joinpath(
    PATH_EXECUTION,
    "outputs", "cuts.json",
)

fcf_cuts_destination = joinpath(PATH_EXECUTION, "cuts.json")

mv(fcf_cuts_file, fcf_cuts_destination; force = true)
#hide

# Now we are ready to run the case in the `MARKET_CLEARING` mode.

# As we need to set the run mode to `MARKET_CLEARING`, we need to open the study again.

db = IARA.load_study(PATH_EXECUTION; read_only = false);

IARA.update_configuration!(
    db;
    bid_data_processing = IARA.Configurations_BiddingGroupBidProcessing.EXTERNAL_UNVALIDATED_BID,
    construction_type_ex_ante_physical = IARA.Configurations_ConstructionType.HYBRID,
    construction_type_ex_ante_commercial = IARA.Configurations_ConstructionType.HYBRID,
    construction_type_ex_post_physical = IARA.Configurations_ConstructionType.HYBRID,
    construction_type_ex_post_commercial = IARA.Configurations_ConstructionType.HYBRID,
)

IARA.link_time_series_to_file(
    db,
    "Configuration";
    fcf_cuts = "cuts.json",
)

IARA.close_study!(db)
; #hide

# Finally, we are ready to run the case.

IARA.market_clearing(
    PATH_EXECUTION;
    delete_output_folder_before_execution = true,
)

# ### Analyzing the results

# The results are stored inside the case folder, in the `outputs` directory.

# ```
# case_folder
#  ├── outputs
#  │    ├── plots
#  │    │   └── ...
#  │    └── ...
#  └── ...
# ```

# According to our results, for the first bid segment, there is more energy generated by the first Asset Owner, which is related to their bidding prices differences.
# The second bid segment has a similar behavior, with the the first asset owner decreasing its energy generation probably due to the decrease in the hydro volume.

# ```@raw html
# <iframe src="case_5_execution\\outputs\\plots\\virtual_reservoir_generation_ex_post_commercial_all.html" style="height:500px;width:100%;"></iframe>
# ```

# Also, the volume from the first hydro unit starts at 100 hm³, and as the energy decreases, the volume decreases as well. The second Hydro unit starts with 0 hm³ and increases over time

# ```@raw html
# <iframe src="case_5_execution\\outputs\\plots\\hydro_initial_volume_ex_post_physical_all.html" style="height:500px;width:100%;"></iframe>
# ```

# Finally, as the second hydro unit has a higher O&M cost, it is only dispatched when the energy from the first hydro unit is not enough to meet the demand.

# ```@raw html
# <iframe src="case_5_execution\\outputs\\plots\\hydro_generation_ex_post_physical_all.html" style="height:500px;width:100%;"></iframe>
# ```
