version = 1
dimensions = ["period", "scenario", "subperiod"]
dimension_size = [1, 1, 2]
initial_date = "2020-01-01 00:00:00"
time_dimension = "period"
frequency = "month"
unit = "GWh"
labels = ["dem_1"]
