version = 1
dimensions = ["season", "scenario", "subperiod"]
dimension_size = [2, 1, 1]
initial_date = "2000-01-01 00:00:00"
time_dimension = "season"
frequency = "month"
unit = "m3/s"
labels = ["gauging_station"]
