name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      iara_url:
        description: 'AWS S3 URL to IARA zip file'
        required: true
        type: string
      version:
        description: 'Release version (e.g., 0.1.0 or 0.1.0-beta.44)'
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    concurrency:
      group: docker

    permissions:
      id-token: write
      contents: read
      attestations: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase organization name
        run: |
          echo "ORG_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ./docker
          file: ./docker/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ env.ORG_LC }}/iara:${{ github.event.inputs.version }}
            ghcr.io/${{ env.ORG_LC }}/iara:latest
          build-args: |
            IARA_URL=${{ github.event.inputs.iara_url }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ghcr.io/${{ env.ORG_LC }}/iara
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
