name: Publish
on:
  workflow_dispatch:
    inputs:
      windows:
        description: "Build windows"
        required: true
        type: boolean
        default: true
      linux:
        description: "Build linux"
        required: true
        type: boolean
        default: true
      development_stage:
        type: choice
        description: "Development stage"
        required: true
        options:
          - Alpha
          - Beta
          - RC
          - Stable
      version_suffix:
        description: "Version suffix (ignored if stable)"
        type: string
        required: false
      psrcloud:
        description: "PSRCloud"
        required: true
        type: boolean
        default: true
      overwrite:
        description: "Overwrite"
        required: true
        type: boolean
        default: false
      docker_only:
        description: "Skip builds and only publish Docker image"
        required: true
        type: boolean
        default: false

env:
  HUB_TOKEN: ${{ secrets.HUB_TOKEN }}
  SLACK_BOT_USER_OAUTH_ACCESS_TOKEN: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}

jobs:
  pre-publish:
    name: Tag check
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: psrenergy/assert-tag@v1

  build-publish-os:
    strategy:
      fail-fast: true
      matrix:
        os: [windows, linux]
    name: Build and publish ${{ matrix.os }}
    needs: [pre-publish]
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v7
        if: inputs[matrix.os] == true
        with:
          fetch-depth: 0

      - uses: astral-sh/setup-uv@v7

      - uses: psrenergy/setup-git-token@v1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Start AWS ECS instance
        if: inputs[matrix.os] == true
        run: julia +1.11.2 --project=./compile ./compile/ecs.jl --development_stage "${{ inputs.development_stage }}" --version_suffix "${{ inputs.version_suffix }}" --overwrite "${{ inputs.overwrite }}" --os ${{ matrix.os }}

      - name: Publish PSRCloud
        if: matrix.os == 'linux' && inputs.psrcloud == true
        run: julia +1.11.2 --project=./compile ./compile/psrcloud.jl --development_stage "${{ inputs.development_stage }}" --version_suffix "${{ inputs.version_suffix }}"

  post-publish:
    if: inputs.development_stage == 'Stable'
    name: Create release
    runs-on: self-hosted
    needs: [build-publish-os]
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: psrenergy/create-tag-and-release@v1

  notify-failure:
    name: Notify Slack on failure
    if: failure()
    needs:
      - pre-publish
      - build-publish-os
      - post-publish
    runs-on: [self-hosted, linux]
    steps:
      - uses: psrenergy/notify-on-failure@v1
        with:
          token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          channel: C05FS4ZJYLU
